### PR TITLE
Add Header Support

### PR DESCRIPTION
**Pull request by anticode-403**

### CODE REVIEW

**Comment by jaumard** [comment]
Hey :) 
Thanks for the contribution! 
Did you test this code ? It doesn't compile at all for me.

**Comment by anticode-403** [comment]
I forgot header was a named prop of Client.get
Resolved.

**Comment by jaumard** [comment]
That still doesn't compile :) that wasn't the only problem  
You have an example app inside the repo to test that it's still working

**Comment by anticode-403** [comment]
I'm not having any issues compiling right now. I'll have to test further when I go into work tomorrow.

**Comment by anticode-403** [comment]
You were right, I wasn't compiling it properly. I've gotten it working on my end. Sorry for the inconvenience.

**Comment by jaumard** [comment]
No problem all good now :) 
Thanks !

**Pull request merged**
